eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
server:
  error:
    whitelabel:
      enabled: false
  port: 8888
  tomcat:
    max-threads: 3
security:
  user:
    name: user
    password: user
logging:
  level:
    com.spring.boot: info
    org: error
    com.netflix : error
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          fail-on-error: false
  application:
    name: config-server
  main:
    banner-mode: 'off'
  profiles:
    active: native
info:
  app:
    name: Config Server
    description: Storing all the configurations.
    version: 1.0.0

